### ISSUE TITLE
16 days countdown?

### ISSUE THREAD

**Issue by clov3r** [mdixon47/Wabisuke#4]
Seems like a short amount of time to build a whole new site to replace this one? We'd better get on it ;)

Have any thoughts for copy, or any blurbs/ mission statements that are already existing to plug in?

**Comment by mdixon47** [comment]
Hey Callum the timer can be rest to whatever we like. I have used Lorem ipsum for the content. That will change soon. I will be working on that for most of the weekend. I will also move the email contact in the contact location.

**Comment by mdixon47** [comment]
Will rest timer as soon as the site is completed and reviewed.
